/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Screens;

import com.entity.Mallar;
import java.awt.Font;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pallas
 */
public final class ScreenAllMallarSelect extends javax.swing.JDialog {

    /**
     * Creates new form ScreenAllMallarSelect
     */
    EntityManager em;
    private DefaultTableModel tmodel;
    private List<Mallar> ListOfMallar;
    public Mallar selectedMallar;
    public ScreenAllMallarSelect(java.awt.Frame parent, boolean modal, EntityManager em) {
        super(parent, modal);
        initComponents();
        this.em = em;
        FillTheMallarTable();
    }
    public void FillTheMallarTable() {
        tmodel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tmodel.addColumn("Adı");
        tmodel.addColumn("Ölçü vahidi");
        tmodel.addColumn("Ştrix Kod");
        tmodel.addColumn("Malın Sinfi");
        tmodel.addColumn("Malın Qrupu");
        tmodel.addColumn("Malın Növü");

        jTableMallar.setAutoResizeMode(jTableMallar.AUTO_RESIZE_ALL_COLUMNS);
        jTableMallar.setRowHeight(20);
        jTableMallar.setFont(new Font("Tahoma", Font.PLAIN, 14));
        jTableMallar.setModel(tmodel);
        ListOfMallar = em.createNamedQuery("Mallar.findAll", Mallar.class).getResultList();

        for (Mallar b : ListOfMallar) {

            tmodel.insertRow(jTableMallar.getRowCount(), new Object[]{
                b.getAdi(),
                b.getIdProperties().getAdi(),
                b.getStrixKod(),
                b.getIdMalNovu().getIdMalQrupu().getIdMalSinfi().getAdi(),
                b.getIdMalNovu().getIdMalQrupu().getAdi(),
                b.getIdMalNovu().getAdi(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMallar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTableMallar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMallar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMallarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMallar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMallarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMallarMouseClicked
        if (evt.getClickCount() == 2) {
            DefaultTableModel model = (DefaultTableModel) jTableMallar.getModel();
            int index = jTableMallar.getSelectedRow();
            selectedMallar = ListOfMallar.get(index);
            this.dispose();
        }
    }//GEN-LAST:event_jTableMallarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMallar;
    // End of variables declaration//GEN-END:variables
}
