/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Screens;

import com.entity.Kassa;
import com.entity.Maganfir;
import com.entity.Malalisqeyiqayt;
import com.entity.Mallar;
import com.entity.Members;
import com.entity.Properties;
import java.util.List;
import java.util.function.Consumer;
import javax.persistence.EntityManager;

/**
 *
 * @author Pallas
 */
public final class ScreenMalAlQaytarAddEdit extends javax.swing.JDialog {

    /**
     * Creates new form ScreenMalAlQaytarAddEdit
     */
    EntityManager em;
    private Mallar SelectedMallar;
    private final List<Maganfir> ListofAnbar;
    private final List<Maganfir> ListofFirma;
    private final List<Properties> ListOfProperties;
    private final List<Members> ListofMembers;
    private Maganfir selectedSatici;
    private Maganfir selectedAnbar;
    private Properties selectedProperties;
    private Members selectedMaliQebulEden;
    private Members selectedSenedleriYigdi;
    private Members selectedTesdiqEtdi;
    
    
    
    public ScreenMalAlQaytarAddEdit(java.awt.Frame parent, boolean modal, EntityManager em) {
        super(parent, modal);
        initComponents();
        this.em = em;
        ListofAnbar = em.createNamedQuery("Maganfir.findByPairentId", Maganfir.class)
                .setParameter("pairentId", "1")
                .getResultList();
        ListofFirma = em.createNamedQuery("Maganfir.findByPairentId", Maganfir.class)
                .setParameter("pairentId", "3")
                .getResultList();
        ListOfProperties = em.createNamedQuery("Properties.findByPairentId", Properties.class)
                .setParameter("pairentId", 2)
                .getResultList();
        ListofMembers = em.createNamedQuery("Members.findByIsActive", Members.class)
                .setParameter("isActive", "1")
                .getResultList();

        jcom();
    }

    public void jcom() {
        ListofFirma.forEach((p) -> {
            jComboBoxSatici.addItem(p.getAdi());
        });
        ListofAnbar.forEach((p) -> {
            jComboBoxAnbar.addItem(p.getAdi());
        });
        ListOfProperties.forEach((Properties p) -> {
            jComboBoxOlcuVahidi.addItem(p.getAdi());
        });
        ListofMembers.forEach((p) -> {
            jComboBoxMaliQebulEden.addItem(p.getAdi() + " " + p.getSoyadi());
        });
        ListofMembers.forEach((p) -> {
            jComboBoxSenedleriYigdi.addItem(p.getAdi() + " " + p.getSoyadi());
        });
        ListofMembers.forEach((p) -> {
            jComboBoxTesdiqEtdi.addItem(p.getAdi() + " " + p.getSoyadi());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSatici = new javax.swing.JComboBox<>();
        jButtonYaddaSaxla = new javax.swing.JButton();
        jButtonBagla = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAnbar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxOlcuVahidi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAlışQiymetiEded = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEDVEded = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEDVCem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAlisQiymetiCem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxMaliQebulEden = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldİnvoysNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxSenedleriYigdi = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxTesdiqEtdi = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldMiqdarı = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Adı");

        jTextFieldAdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Satıcı");

        jComboBoxSatici.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSatici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSaticiActionPerformed(evt);
            }
        });

        jButtonYaddaSaxla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonYaddaSaxla.setText("Yadda saxla");
        jButtonYaddaSaxla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYaddaSaxlaActionPerformed(evt);
            }
        });

        jButtonBagla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBagla.setText("Bağla");
        jButtonBagla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaglaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Anbar");

        jComboBoxAnbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxAnbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnbarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ölçü vahidi");

        jComboBoxOlcuVahidi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxOlcuVahidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOlcuVahidiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Alış Qiyməti (Ədəd)");

        jTextFieldAlışQiymetiEded.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ƏDV (Ədəd)");

        jTextFieldEDVEded.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ƏDV (Cəm)");

        jTextFieldEDVCem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Alış Qiyməti (Cəm)");

        jTextFieldAlisQiymetiCem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Malı Qəbul Edən");

        jComboBoxMaliQebulEden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMaliQebulEden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaliQebulEdenActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("İnvoys Nömrəsi");

        jTextFieldİnvoysNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sənədləri Yığdı");

        jComboBoxSenedleriYigdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSenedleriYigdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSenedleriYigdiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Təsdiq etdi");

        jComboBoxTesdiqEtdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTesdiqEtdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTesdiqEtdiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Miqdarı");

        jTextFieldMiqdarı.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Seç");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonYaddaSaxla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBagla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxOlcuVahidi, 0, 336, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMiqdarı, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAdi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAnbar, 0, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSatici, 0, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAlışQiymetiEded, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEDVEded, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAlisQiymetiCem, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEDVCem, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMaliQebulEden, 0, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldİnvoysNo, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSenedleriYigdi, 0, 336, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTesdiqEtdi, 0, 336, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSatici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxAnbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxOlcuVahidi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldMiqdarı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAlışQiymetiEded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEDVEded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAlisQiymetiCem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEDVCem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxMaliQebulEden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldİnvoysNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxSenedleriYigdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxTesdiqEtdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBagla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonYaddaSaxla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonYaddaSaxlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYaddaSaxlaActionPerformed
        java.util.Date date = new java.util.Date();
        long t = date.getTime();
        java.sql.Date sqlDate = new java.sql.Date(t);
        if (SelectedMallar != null) {
            Malalisqeyiqayt maq = new Malalisqeyiqayt(0);
            maq.setTarix(sqlDate);
            maq.setIdFirma(em.find(Maganfir.class, selectedSatici.getIdMagAnFir()));
            maq.setIdMallar(em.find(Mallar.class, SelectedMallar.getIdMallar()));
            maq.setIdAnbar(em.find(Maganfir.class, selectedAnbar.getIdMagAnFir()));
            maq.setIdProperties(em.find(Properties.class, selectedProperties.getIdProperties()));
            maq.setMiqdari(jTextFieldMiqdarı.getText());
            maq.setAlisQiymeti(Double.parseDouble(jTextFieldAlışQiymetiEded.getText()));
            maq.setEdv(Double.parseDouble(jTextFieldEDVEded.getText()));
                        
            Kassa k = new Kassa(0);
            k.setTarix(sqlDate);
            k.setMedaxil(0);
            k.setMexaric(Double.parseDouble(jTextFieldAlisQiymetiCem.getText()));
            k.setPairentId("1");
            k.setInsertId(SelectedMallar.getIdMallar().toString());
            k.setQeyd("1");
            em.persist(k);
            em.getTransaction().begin();
            em.getTransaction().commit();
                        
            Object a = em.createQuery("select max(u.idKassa) from Kassa u", Integer.class).getSingleResult();

            Kassa ke = new Kassa(0);
            ke.setTarix(sqlDate);
            ke.setMedaxil(0);
            ke.setMexaric(Double.parseDouble(jTextFieldEDVCem.getText()));
            ke.setPairentId("1");
            ke.setInsertId(SelectedMallar.getIdMallar().toString());
            ke.setQeyd("2");
            em.persist(ke);
            em.getTransaction().begin();
            em.getTransaction().commit();
            
            Object b = em.createQuery("select max(u.idKassa) from Kassa u", Integer.class).getSingleResult();
            
            maq.setIdKassaAlisQIyCem(em.find(Kassa.class, a));
            maq.setIdKassaCemEDV(em.find(Kassa.class, b));
            maq.setIdMembersQebul(em.find(Members.class, selectedMaliQebulEden.getIdMembers()));
            maq.setInvoysNo(jTextFieldİnvoysNo.getText());
            maq.setIdMembersSenedYigan(em.find(Members.class, selectedSenedleriYigdi.getIdMembers()));
            maq.setIdMembersTesdiqEden(em.find(Members.class, selectedTesdiqEtdi.getIdMembers()));
            maq.setPairentid(1);
            em.persist(maq);
            em.getTransaction().begin();
            em.getTransaction().commit();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonYaddaSaxlaActionPerformed

    private void jButtonBaglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaglaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBaglaActionPerformed

    private void jComboBoxSaticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSaticiActionPerformed
        if (jComboBoxSatici.getSelectedIndex() > -1) {
            selectedSatici = ListofFirma.get(jComboBoxSatici.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxSaticiActionPerformed

    private void jComboBoxAnbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnbarActionPerformed
        if (jComboBoxAnbar.getSelectedIndex() > -1) {
            selectedAnbar = ListofAnbar.get(jComboBoxAnbar.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxAnbarActionPerformed

    private void jComboBoxOlcuVahidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOlcuVahidiActionPerformed
        if (jComboBoxOlcuVahidi.getSelectedIndex() > -1) {
            selectedProperties = ListOfProperties.get(jComboBoxOlcuVahidi.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxOlcuVahidiActionPerformed

    private void jComboBoxMaliQebulEdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaliQebulEdenActionPerformed
        if (jComboBoxMaliQebulEden.getSelectedIndex() > -1) {
            selectedMaliQebulEden = ListofMembers.get(jComboBoxMaliQebulEden.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxMaliQebulEdenActionPerformed

    private void jComboBoxSenedleriYigdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSenedleriYigdiActionPerformed
        if (jComboBoxSenedleriYigdi.getSelectedIndex() > -1) {
            selectedSenedleriYigdi = ListofMembers.get(jComboBoxSenedleriYigdi.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxSenedleriYigdiActionPerformed

    private void jComboBoxTesdiqEtdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTesdiqEtdiActionPerformed
        if (jComboBoxTesdiqEtdi.getSelectedIndex() > -1) {
            selectedTesdiqEtdi = ListofMembers.get(jComboBoxTesdiqEtdi.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxTesdiqEtdiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ScreenAllMallarSelect  d = new ScreenAllMallarSelect(null, rootPaneCheckingEnabled, em);
        d.setVisible(rootPaneCheckingEnabled);
        SelectedMallar = d.selectedMallar;
        jTextFieldAdi.setText(SelectedMallar.getAdi());
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBagla;
    private javax.swing.JButton jButtonYaddaSaxla;
    private javax.swing.JComboBox<String> jComboBoxAnbar;
    private javax.swing.JComboBox<String> jComboBoxMaliQebulEden;
    private javax.swing.JComboBox<String> jComboBoxOlcuVahidi;
    private javax.swing.JComboBox<String> jComboBoxSatici;
    private javax.swing.JComboBox<String> jComboBoxSenedleriYigdi;
    private javax.swing.JComboBox<String> jComboBoxTesdiqEtdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldAlisQiymetiCem;
    private javax.swing.JTextField jTextFieldAlışQiymetiEded;
    private javax.swing.JTextField jTextFieldEDVCem;
    private javax.swing.JTextField jTextFieldEDVEded;
    private javax.swing.JTextField jTextFieldMiqdarı;
    private javax.swing.JTextField jTextFieldİnvoysNo;
    // End of variables declaration//GEN-END:variables
}
